#!/usr/bin/env bun
import { join } from "node:path";
import snippetData from "../src/content/regex-snippets.toml";
import { snippetSchema } from "../src/features/snippet-library/schema.ts";

const contentDir = join(import.meta.dir, "..", "src", "content");

function fail(message: string): never {
  process.stderr.write(`build-content: ${message}\n`);
  process.exit(1);
}

async function buildDocument(slug: string) {
  const markdownHtml = (
    Bun as unknown as { markdown?: { html?: (md: string) => string } }
  ).markdown?.html;
  if (typeof markdownHtml !== "function") {
    fail(
      "Bun.markdown.html is unavailable; use the Bun version in .bun-version."
    );
  }
  const md = await Bun.file(join(contentDir, `${slug}.md`)).text();
  const html = markdownHtml(md);
  return { html, markdown: md };
}

async function buildSnippets() {
  const raw = (snippetData as { snippet?: unknown[] }).snippet;
  if (!Array.isArray(raw) || raw.length === 0) {
    fail("regex-snippets.toml has no [[snippet]] entries.");
  }
  const snippets = raw.map((entry, index) => {
    const parsed = snippetSchema.safeParse(entry);
    if (!parsed.success) {
      fail(
        `snippet #${index} is invalid: ${parsed.error.issues
          .map((issue) => `${issue.path.join(".")} ${issue.message}`)
          .join("; ")}`
      );
    }
    try {
      new RegExp(parsed.data.pattern);
    } catch (error) {
      fail(
        `snippet #${index} pattern is not a valid regex (${parsed.data.pattern}): ${(error as Error).message}`
      );
    }
    return { id: `${parsed.data.group}-${index}`, ...parsed.data };
  });

  const toml = await Bun.file(join(contentDir, "regex-snippets.toml")).text();
  return { snippets, toml };
}

const [cookbook, rules, snippets] = await Promise.all([
  buildDocument("cookbook"),
  buildDocument("format-rules"),
  buildSnippets(),
]);
await Promise.all([
  Bun.write(
    join(contentDir, "cookbook-snippets.generated.json"),
    JSON.stringify({ ...cookbook, ...snippets })
  ),
  Bun.write(
    join(contentDir, "format-rules.generated.json"),
    JSON.stringify(rules)
  ),
]);
await Bun.write(
  join(contentDir, "reference.generated.ts"),
  `// Generated by scripts/build-content.ts; do not edit.
import type { RegexSnippet } from "@/features/snippet-library/schema";
import { loadData } from "./load-data";
const [catalog, rules] = await Promise.all([
  loadData<{ html: string; markdown: string; snippets: RegexSnippet[]; toml: string }>("cookbook-snippets"),
  loadData<{ html: string; markdown: string }>("format-rules"),
]);
export const COOKBOOK_HTML = catalog.html;
export const COOKBOOK_MARKDOWN = catalog.markdown;
export const FORMAT_RULES_HTML = rules.html;
export const FORMAT_RULES_MARKDOWN = rules.markdown;
export const REGEX_SNIPPETS = catalog.snippets;
export const SNIPPETS_TOML = catalog.toml;
`
);
process.stdout.write(
  "build-content: generated cookbook + format rules + snippet catalog\n"
);
