#!/usr/bin/env bun
// Build-time content pipeline (ADR-0009). Run with the project's Bun (via mise),
// where Bun.markdown is available. Generates external JSON data and small loader
// modules; each markdown document also ships its raw source, which the
// prompt package consumes (ADR-0016):
//   src/content/reference.generated.ts — typed exports loaded together
import { join } from "node:path";
import snippetData from "../src/content/regex-snippets.toml";
import { snippetSchema } from "../src/features/snippet-library/schema.ts";

const contentDir = join(import.meta.dir, "..", "src", "content");

function fail(message: string): never {
  process.stderr.write(`build-content: ${message}\n`);
  process.exit(1);
}

const GENERATED_HEADER =
  "// AUTO-GENERATED by scripts/build-content.ts — do not edit. See ADR-0009.\n";

// Renders one markdown document to external JSON, emitting both the HTML
// the app renders and the raw markdown the prompt package embeds (ADR-0016).
async function buildDocument(slug: string): Promise<void> {
  const markdownHtml = (
    Bun as unknown as { markdown?: { html?: (md: string) => string } }
  ).markdown?.html;
  if (typeof markdownHtml !== "function") {
    fail(
      "Bun.markdown.html is unavailable — run with the project's Bun via mise (1.3.12), not the global ~/.bun (1.3.6)."
    );
  }
  const md = await Bun.file(join(contentDir, `${slug}.md`)).text();
  const html = markdownHtml(md);
  await Bun.write(
    join(contentDir, `${slug}.generated.json`),
    JSON.stringify({ html, markdown: md })
  );
}

async function buildSnippets(): Promise<void> {
  const raw = (snippetData as { snippet?: unknown[] }).snippet;
  if (!Array.isArray(raw) || raw.length === 0) {
    fail("regex-snippets.toml has no [[snippet]] entries.");
  }
  const snippets = raw.map((entry, index) => {
    const parsed = snippetSchema.safeParse(entry);
    if (!parsed.success) {
      fail(
        `snippet #${index} is invalid: ${parsed.error.issues
          .map((issue) => `${issue.path.join(".")} ${issue.message}`)
          .join("; ")}`
      );
    }
    try {
      new RegExp(parsed.data.pattern);
    } catch (error) {
      fail(
        `snippet #${index} pattern is not a valid regex (${parsed.data.pattern}): ${(error as Error).message}`
      );
    }
    return { id: `${parsed.data.group}-${index}`, ...parsed.data };
  });

  const toml = await Bun.file(join(contentDir, "regex-snippets.toml")).text();
  await Bun.write(
    join(contentDir, "snippets.generated.json"),
    JSON.stringify({ snippets, toml })
  );
}

await Promise.all([
  buildDocument("cookbook"),
  buildDocument("format-rules"),
  buildSnippets(),
]);
await Bun.write(
  join(contentDir, "reference.generated.ts"),
  `${GENERATED_HEADER}
import type { RegexSnippet } from "@/features/snippet-library/schema";
import { loadData } from "./load-data";
const [cookbook, rules, snippets] = await Promise.all([
  loadData<{ html: string; markdown: string }>("cookbook"),
  loadData<{ html: string; markdown: string }>("format-rules"),
  loadData<{ snippets: RegexSnippet[]; toml: string }>("snippets"),
]);
export const COOKBOOK_HTML = cookbook.html;
export const COOKBOOK_MARKDOWN = cookbook.markdown;
export const FORMAT_RULES_HTML = rules.html;
export const FORMAT_RULES_MARKDOWN = rules.markdown;
export const REGEX_SNIPPETS = snippets.snippets;
export const SNIPPETS_TOML = snippets.toml;
`
);
process.stdout.write(
  "build-content: generated cookbook + format rules + snippet catalog\n"
);
