#!/usr/bin/env bun
// Build-time content pipeline (ADR-0009). Run with the project's Bun (via mise),
// where Bun.markdown is available. Generates three gitignored modules consumed by
// the client bundle; each markdown document also ships its raw source, which the
// prompt package consumes (ADR-0016):
//   src/content/cookbook.generated.ts      — COOKBOOK_HTML + COOKBOOK_MARKDOWN
//   src/content/format-rules.generated.ts  — FORMAT_RULES_HTML + FORMAT_RULES_MARKDOWN
//   src/content/snippets.generated.ts      — REGEX_SNIPPETS + SNIPPETS_TOML
import { join } from "node:path";
import snippetData from "../src/content/regex-snippets.toml";
import { snippetSchema } from "../src/features/snippet-library/schema.ts";

const contentDir = join(import.meta.dir, "..", "src", "content");

function fail(message: string): never {
  process.stderr.write(`build-content: ${message}\n`);
  process.exit(1);
}

const GENERATED_HEADER =
  "// AUTO-GENERATED by scripts/build-content.ts — do not edit. See ADR-0009.\n";

// Renders one markdown document to `<SLUG>.generated.ts`, emitting both the HTML
// the app renders and the raw markdown the prompt package embeds (ADR-0016).
async function buildDocument(slug: string, constPrefix: string): Promise<void> {
  const markdownHtml = (
    Bun as unknown as { markdown?: { html?: (md: string) => string } }
  ).markdown?.html;
  if (typeof markdownHtml !== "function") {
    fail(
      "Bun.markdown.html is unavailable — run with the project's Bun via mise (1.3.12), not the global ~/.bun (1.3.6)."
    );
  }
  const md = await Bun.file(join(contentDir, `${slug}.md`)).text();
  const html = markdownHtml(md);
  const out =
    `${GENERATED_HEADER}export const ${constPrefix}_HTML = ${JSON.stringify(html)};\n\n` +
    `export const ${constPrefix}_MARKDOWN = ${JSON.stringify(md)};\n`;
  await Bun.write(join(contentDir, `${slug}.generated.ts`), out);
}

async function buildSnippets(): Promise<void> {
  const raw = (snippetData as { snippet?: unknown[] }).snippet;
  if (!Array.isArray(raw) || raw.length === 0) {
    fail("regex-snippets.toml has no [[snippet]] entries.");
  }
  const snippets = raw.map((entry, index) => {
    const parsed = snippetSchema.safeParse(entry);
    if (!parsed.success) {
      fail(
        `snippet #${index} is invalid: ${parsed.error.issues
          .map((issue) => `${issue.path.join(".")} ${issue.message}`)
          .join("; ")}`
      );
    }
    try {
      new RegExp(parsed.data.pattern);
    } catch (error) {
      fail(
        `snippet #${index} pattern is not a valid regex (${parsed.data.pattern}): ${(error as Error).message}`
      );
    }
    return { id: `${parsed.data.group}-${index}`, ...parsed.data };
  });

  const toml = await Bun.file(join(contentDir, "regex-snippets.toml")).text();
  const out =
    `${GENERATED_HEADER}import type { RegexSnippet } from "@/features/snippet-library/schema";\n\n` +
    `export const REGEX_SNIPPETS: RegexSnippet[] = ${JSON.stringify(snippets, null, 2)};\n\n` +
    `export const SNIPPETS_TOML = ${JSON.stringify(toml)};\n`;
  await Bun.write(join(contentDir, "snippets.generated.ts"), out);
}

await Promise.all([
  buildDocument("cookbook", "COOKBOOK"),
  buildDocument("format-rules", "FORMAT_RULES"),
  buildSnippets(),
]);
process.stdout.write(
  "build-content: generated cookbook + format rules + snippet catalog\n"
);
